spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBEP}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
#    show-sql:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging.level:
  org.hibernate.SQL: trace
  org.springframework.security: error

token:
  secret: ${TOKEN_SECRET}
  expirationTime: ${TIME}

jwt:
  key:
    secret: ${JWT_SECRET}